files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  no-ids: 0
  nesting-depth:
    - 2
    - max-depth: 4
  no-vendor-prefixes: 0
  no-misspelled-properties:
    - 1
    - extra-properties:
      - touch-callout
